wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.17.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1724001733
    t:
      1:
      - 1
      - 5
      - 37
      - 38
      - 41
      - 53
      - 55
      - 82
      2:
      - 1
      - 5
      - 37
      - 38
      - 41
      - 53
      - 55
      - 82
      3:
      - 23
      4: 3.10.14
      5: 0.17.0
      8:
      - 5
      13: linux-x86_64
